# Numpy

1. Creating Arrays

In [3]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5]) #1D array
arr_2d = np.array([[1,2,3],[4,5,6]]) #2D array
arr_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) #3D array

2. Array Attributes

In [6]:
print(arr_1d.shape)
print(arr_2d.shape)
print(arr_3d.shape)

(5,)
(2, 3)
(2, 2, 2)


 3. Indexing and Slicing
 

In [8]:
# Used for accessing elements

Numbers = np.array([1, 2, 3, 4, 5])
print(Numbers[0]) # 1
print(Numbers[1:4]) # [2 3 4]
print(Numbers[1:4:2]) # [2 4] - step of 2
print(Numbers[-1]) # 5 - last element
print(Numbers[Numbers>2]) # [3 4 5] - boolean indexing


1
[2 3 4]
[2 4]
5
[3 4 5]


3. Array Operations

In [9]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(a + b)
print(a * b) # Element-wise multiplication
print(a ** 2)
print(np.sqrt(a)) # Square root of each element


[ 7  9 11 13 15]
[ 6 14 24 36 50]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]


4. 