# Numpy

1. Creating Arrays

In [18]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5]) #1D array
arr_2d = np.array([[1,2,3],[4,5,6]]) #2D array
arr_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) #3D array

2. Array Attributes

In [19]:
print(arr_1d.shape)
print(arr_2d.shape)
print(arr_3d.shape)

(5,)
(2, 3)
(2, 2, 2)


 3. Indexing and Slicing
 

In [20]:
# Used for accessing elements

Numbers = np.array([1, 2, 3, 4, 5])
print(Numbers[0]) # 1
print(Numbers[1:4]) # [2 3 4]
print(Numbers[1:4:2]) # [2 4] - step of 2
print(Numbers[-1]) # 5 - last element
print(Numbers[Numbers>2]) # [3 4 5] - boolean indexing


1
[2 3 4]
[2 4]
5
[3 4 5]


4. Array Operations

In [21]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(a + b)
print(a * b) # Element-wise multiplication
print(a ** 2)
print(np.sqrt(a)) # Square root of each element


[ 7  9 11 13 15]
[ 6 14 24 36 50]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]


5. Aggregation Function

In [22]:
datas = np.array([10,20,40,50,80])

print(datas.mean()) # Mean
print(datas.std()) # Standard deviation
print(datas.var()) # Variance
print(datas.min()) # Minimum
print(datas.max()) # Maximum
print(datas.sum()) # Sum of all elements
print(datas.cumsum()) # Cumulative sum

40.0
24.49489742783178
600.0
10
80
200
[ 10  30  70 120 200]


6. Reshape and Transpose


In [23]:
arr = np.array([1,2,3,5,78,42])
reshaped = arr.reshape(2,3) # Reshape to 2 rows and 3 columns
print(reshaped)
print(reshaped.T) # Transpose the reshaped array


[[ 1  2  3]
 [ 5 78 42]]
[[ 1  5]
 [ 2 78]
 [ 3 42]]


7. Random Module

In [24]:
np.random.seed(0)   # for reproducibility
rand_nums = np.random.rand(3)   # [0.5488, 0.7152, 0.6027]

# Random integers between 0–10
rand_ints = np.random.randint(0, 10, size=5)  # [5, 0, 3, 3, 7]


8. Stacking Arrays

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

print(np.vstack([a, b]))
# [[1 2]
#  [3 4]]

[[1 2]
 [3 4]]


9. Dot Product

In [26]:
a = np.array([1, 2])
b = np.array([3, 4])

print(np.dot(a, b))  


11
